### ISSUE TITLE
Existing "Solutions" ?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/crockery-drying-storage-rack#2]
- **Joseph Joseph Connect Modular Dish Rack**: http://www.johnlewis.com/joseph-joseph-connect-modular-dish-rack/p1591519 £**25**
  ![joseph-joseph-modular-dish-rack](https://cloud.githubusercontent.com/assets/194400/7516902/f01e9c46-f4c9-11e4-9a06-11cf3db78797.png)
- **SimpleHuman Brushed Steel rack**: https://www.amara.com/products/brushed-steel-grey-dish-rack-wine-glass-holder £**65**
  ![simple-human-dish-rack](https://cloud.githubusercontent.com/assets/194400/7516867/c629f23c-f4c9-11e4-836a-f3d9df533234.png)

**Comment by missinglink** [comment]
:+1:

**Comment by nelsonic** [comment]
My main gripe is the fact that the existing "_solutions_" are designed for single people. (i.e. _tiny_!)
our work space has 30+ people so the rack is _always_ full and requires constant packing away...
The act of packing away dishes takes _millions_ of people minutes each day.
What could you do with a **_million minutes**_...? :wink:

**Comment by missinglink** [comment]
https://www.pinterest.com/pin/4785143330064561/
![drying rack](https://s-media-cache-ak0.pinimg.com/736x/79/9c/79/799c793c181c5117d854cd6364ecf5d5.jpg)

**Comment by missinglink** [comment]
Sounds like having the drying rack as the same place you 'store' everything is ideal

**Comment by nelsonic** [comment]
Saves _so *_much*\* time\* (_in the long run_) ...!

**Comment by missinglink** [comment]
This is what commercial kitchens use:
![pic](http://www.kitchenequipmentaustralia.com.au/images/lrg/item_1737_1.jpg)

**Comment by nelsonic** [comment]
Yeah, the Pros know dishes are a bottleneck.
I'm going to _solve_ this for us (and then _the whole world_!) 
![todo list](http://www.homeschoolmarketplace.com/images/pinkyandbrain3.jpg)

**Comment by missinglink** [comment]
as an MVP, you could get 2x of the 'commercial' ones I linked above for cheap and stick some wooden 'risers' in each corner to elevate the second above the first (with enough room to enter/exit plates) and then go straight to user testings. #lean

[edit] plus a bucket underneath to catch the drips

**Comment by missinglink** [comment]
oh just realised that the second level will catch drips from the first #possiblynotideal

**Comment by nelsonic** [comment]
Yea, the plastic commercial ones _would_ make a good MVP.
I was thinking of making a modular system that would have stainless steel mesh:
![stainless-steel-mesh](https://cloud.githubusercontent.com/assets/194400/7516197/6ae3a84a-f4c5-11e4-899b-a30440f00933.png)
At a slight angle so drops of water are guided to the side and thus items in lower racks would not get wet by freshly washed items stacked in a higher rack...

**Comment by missinglink** [comment]
sounds like a bit of work but you'd probably get a solution more suited to your specific domain (kitchen), this sort of thing is also nice:
![image](http://aladdintemprite.com/media/catalog/product/cache/1/image/800x600/9df78eab33525d08d6e5fb8d27136e95/j/1/j164r-11609_1.jpg)

**Comment by nelsonic** [comment]
Yeah, the trolley design is good for portability in catering.
But in a domestic kitchen we want integrate the rack into an existing 60x35cm cabinet. 
That way we can retrofit _all_ the Kitchens Ikea, Magnet, etc have sold to people.
Granted _many_ people use dish washers instead of _manually_ washing dishes and putting them on a rack. But I suspect the market is still a couple of thousand units...

One of the most important considerations is a discrete design.
I quite like the combo of (Ply) Wood, Stainless Steel and White Plastic.
![mdc-kitchen-counter-drying-rack](https://cloud.githubusercontent.com/assets/194400/7516330/83ca9296-f4c6-11e4-82de-778c17b1c598.jpg)

**Comment by missinglink** [comment]
woh woh woh mind blown!
http://blog.2modern.com/2014/08/ny-now-sod-drying-rack-by-finell.html

![rack](http://blog.2modern.com/wp-content/uploads/2014/08/Sod_Green_Context-Full.jpg)

**Comment by nelsonic** [comment]
Yeah, the trolley design is good for portability in catering.
But in a domestic kitchen we want integrate the rack into an existing 60x35cm cabinet. 
That way we can retrofit *all* the Kitchens Ikea, Magnet, etc have sold to people.
Granted *many* people use dish washers instead of *manually* washing dishes and putting them on a rack. But I suspect the market is still a couple of thousand units...

**Comment by nelsonic** [comment]
Yeah, the Finell (Sod) Drying Rack is super stylish. (_and_ **_correspondingly pricey**_!)

![finell-dish-rack](https://cloud.githubusercontent.com/assets/194400/7516968/3ea5c998-f4ca-11e4-8881-b69c0031fb6d.png)

After 6 months of dust mixed with water (i.e gunk) its virtually impossible to clean and starts to look manky... but the _design_ is _boss_! I guess you could "just stick it in the dishwasher" to get the bristles clean. but then why would you have a fancy dish rack if you have a dish washer...? :wink:

**Comment by missinglink** [comment]
these things would also save you some serious seconds:

![pic](https://secure.contactdesigns.net/disabilityproducts.com/htdocs/contactcommerce/images/items/bbottle.JPG)

![pic2](http://industrial-warewashers.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/t/w/twin-go-3.jpg)

**Comment by missinglink** [comment]
my mother has one of these, super awesome, its called a `dishwasher` (not cheap), you can run one drawer at a time:

![dishwasher](http://p-fst1.pixstatic.com/5069ffea74c5b64af7000b26._w.1500_s.fit_.jpg)

**Comment by nelsonic** [comment]
lol. I used one of those **glass washers** (_a lot_!) in the summer of 2004 (when _one_ of my jobs was dish washer...) #memories ;-)
Good when you need to wash single glasses fast at scale. Not many households will have them.

**Comment by nelsonic** [comment]
yeah, that dual-drawer dish washer is _sweet_. defs not cheap.
And still needs to be unpacked by someone tho...
There are _millions_ of homes that have dishwashers (machines) they are "_sorted_".
There are _way_ more people that _don't_ and would have to re-do their kitchens to fit one in (plumbing, electrics etc)
What I'm proposing is a way to retrofit existing kitchens with a space/time saving rack that will cost roughly £200 and **_pay for its self**_ in the **_time**_ you **_save**_ _packing away dishes_ in less than a year. :wink:

**Comment by missinglink** [comment]
http://www.amazon.com/gp/product/B004TS7SHM/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B004TS7SHM&linkCode=as2&tag=interfacts0b-20&linkId=BNBVUTZ2OHF3DPEK

**Comment by missinglink** [comment]
@nelsonic what's the status of this issue, can we mark it as resolved?

**Comment by nelsonic** [comment]
Good question @missinglink ...
Are you having a clean-up of all issues you're a participant in? :-)
Yes, lets close the issue, I can re-open or create a new one when I have time to _solve_ the problem.
Hope you are well.

**Comment by missinglink** [comment]
so... 2 years later I have finally spotted the perfect solution @nelsonic!

![rack](https://images-na.ssl-images-amazon.com/images/I/51kTOzzd7-L.jpg)

[amazon link](https://www.amazon.de/lzzfw-Wasserfilter-Sch%C3%BCssel-Bew%C3%A4sserungskugeln-Essst%C3%A4bchen/dp/B071V8HR15/ref=sr_1_89?ie=UTF8&qid=1495272141&sr=8-89&keywords=water+filter+kitchen)

**Comment by nelsonic** [comment]
@missinglink sweet rack! thanks for sharing! 🎉
